btkakademidjangoatolye2024/btkakademidjangoatolye2024/urls.py
from django.contrib import admin
from django.urls import include, path
from kullanicilar import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('restoran.urls')),
    path('restoran/', include('restoran.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='kullanicilar/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='kullanicilar/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    
]




urlpatterns += [
    # ... the rest of your URLconf goes here ...
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

btkakademidjangoatolye2024/restoran/urls.py
from . import views
from django.urls import path
from .views import detail,item_detail,add_comment

app_name = 'restoran' # namespace

urlpatterns = [
    path('',views.IndexClassView.as_view(),name='index'),
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('item/',views.item,name='item'),
    # item ekleme
    path('add',views.CreateItem.as_view(),name='create_item'),
    # düzenleme
    path('update/<int:id>',views.update_item,name='update_item'),
    # silme
    path('delete/<int:id>',views.delete_item,name='delete_item'),
    path('item/<int:item_id>/', item_detail, name='item_detail'),
    path('item/<int:item_id>/add_comment/', add_comment, name='add_comment'),
    

]

btkakademidjangoatolye2024/kullanicilar/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.created_at}'

btkakademidjangoatolye2024/restoran/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):
 
    
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1,related_name='kullanicilar')
    item_name = models.CharField(max_length=255)
    item_description = models.CharField(max_length=255)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default='')

    def __str__(self):
        return self.item_name
    

    def get_absolute_url(self):
        return reverse("restoran:detail", kwargs={"pk": self.pk})
    
class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='restoran_comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)    
    

btkakademidjangoatolye2024/kullanicilar/forms.py
from django import forms 
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm
from .models import Comment

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User 
        fields = ['username','email','password1','password2']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']        

btkakademidjangoatolye2024/restoran/forms.py
from django import forms 
from .models import Item, Comment

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item 
        fields = ['item_name','item_description','item_price','item_image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']        

btkakademidjangoatolye2024/kullanicilar/views.py
from django.shortcuts import redirect,render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Profile,Comment
from .forms import RegisterForm,CommentForm
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Kayıt işlemi BAŞARILI : {username}, hoşgeldiniz')
            return redirect('login')
    else:
        form = RegisterForm()
    return render (request,'kullanicilar/register.html',{'form':form})        
         
@login_required
def profilepage(request):
    return render(request,'kullanicilar/profile.html')  

@login_required
def profile_detail(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    comments = profile.comments.all()  

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.profile = profile
            comment.save()
            return redirect('profile_detail', profile_id=profile_id)
    else:
        form = CommentForm()

    return render(request, 'profile_detail.html', {'profile': profile, 'comments': comments, 'form': form})

btkakademidjangoatolye2024/restoran/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item, Comment
from django.template import loader
from .forms import ItemForm, CommentForm
from django.views.generic.list import ListView 
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    item_list = Item.objects.all()
    template = loader.get_template('restoran/index.html')
    context = {
        'item_list' : item_list,
    }
    return render(request,'restoran/index.html',context)


class IndexClassView(ListView):
    model = Item;
    template_name = 'restoran/index.html'
    context_object_name = 'item_list'


def item (request):
    return HttpResponse('<h1>Bu bir item viewi</h1>')

def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request,'restoran/detail.html',context)    

class FoodDetail(DetailView):
    model = Item
    template_name = 'restoran/detail.html'

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('restoran:index')
    
    return render(request,'restoran/item-form.html',{'form':form})


class CreateItem(CreateView):
    model = Item;
    fields = ['item_name','item_description','item_price','item_image']
    template_name='restoran/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    
    if form.is_valid():
        form.save()
        return redirect('restoran:index')
    
    return render(request,'restoran/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('restoran:index')
    return render(request,'restoran/item-delete.html',{'item':item})

def item_detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    comments = Comment.objects.filter(item=item)
    form = CommentForm()

    context = {'item': item, 'comments': comments, 'form': form}
    return render(request, 'restoran/item_detail.html', context)

@login_required
def add_comment(request, item_id):
    item = Item.objects.get(pk=item_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.item = item
            comment.user = request.user
            comment.save()
            return redirect('restoran:item_detail', item_id=item_id)

    return redirect('restoran:item_detail', item_id=item_id)

btkakademidjangoatolye2024/kullanicilar/templates/kullanicilar/login.html
{% extends 'restoran/base.html' %}

{% block body %}




<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-warning">
                   <div class="card-title">
                      Giriş Yap
                   </div>
                </div>  
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn-warning" type="submit">Giriş Yap</button>
                    </form> 
                </div>    
            </div>    
        </div>
    </div>
</div>        
{% endblock %}

btkakademidjangoatolye2024/kullanicilar/templates/kullanicilar/logout.html
{% extends 'restoran/base.html' %}

{% block body %}


{% comment %} <form method="POST">
   <h1>Çıkış işlemi BAŞARILI</h1>
</form>    {% endcomment %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Çıkış İşlemi Başarılı</title>
    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh; 
            margin: 0; 
            background-color: #f2f2f2; 
        }

        form {
            text-align: center; 
        }
    </style>
</head>
<body>
    <form method="POST">
        <h1>....Çıkış İşlemi BAŞARILI</h1>
    </form>
</body>
</html>


{% endblock %}

btkakademidjangoatolye2024/kullanicilar/templates/kullanicilar/profile.html
{% extends 'restoran/base.html' %}

{% block body %}


<h1>{{ user.username }}</h1>
<img height ="300px" widht="500px" src="{{ user.profile.image.url }}">


{% endblock %}

btkakademidjangoatolye2024/kullanicilar/templates/kullanicilar/register.html
{% extends 'restoran/base.html' %}

{% block body %}




<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-success">
                   <div class="card-title">
                      Kayıt Ol 
                   </div>
                </div>  
                <div class="card-body">
                    <form method='POST'>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{ field.name }}
                            <br>
                            {{field}}
                        </div>
                        {% endfor %}
                        <button class="btn-success" type="submit">Kayıt Ol</button>
                    </form>    
                </div>    
            </div>    
        </div>
    </div>
</div>        
{% endblock %}

btkakademidjangoatolye2024/restoran/templates/restoran/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'restoran/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Sedat Kerem ÖZKAN - Restoran</title>
    
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand"> Restoran Uygulaması </a>
        <div class="navbar">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link text-info" href="{% url 'restoran:create_item' %}">Ürün Ekle</a>
                <a class="nav-item nav-link text-warning" href="{% url 'profile' %}">Profilim</a>
                <a class="nav-item nav-link text-danger" href="{% url 'logout' %}">Çıkış Yap</a>
            {% else %}
                <a class="text-warning" href="{% url 'login' %}">Giriş Yap</a>
                <a class="nav-item nav-link text-success" href="{% url 'register' %}">Kayıt Ol</a>
            {% endif %}
        </div>
    </nav>

    
    
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>    
        {% endfor %}
    {% endif %}  

    

    {% block body %}
    
    
    
    {% endblock %}

    
<!-- Footer -->
<footer>
    <div class="container container-dark bg-dark">
        <div class="row">
            <!-- Hızlı Linkler -->
            <div class="col-md-2 footer-section">
                <h4>Hızlı Linkler</h4>
                <ul class="list-unstyled footer-links">
                    <li><a href="#">Anasayfa</a></li>
                    <li><a href="#">Hakkımızda</a></li>
                    <li><a href="#">Hizmetler</a></li>
                    <li><a href="#">İletişim</a></li>
                </ul>
            </div>
            <!-- Sosyal Medya -->
            <div class="col-md-4 footer-section">
                <h4>Sosyal Medya</h4>
                <ul class="list-unstyled footer-social">
                    <li><a href="#" target="_blank"><i class="fab fa-facebook"></i> Facebook</a></li>
                    <li><a href="#" target="_blank"><i class="fab fa-twitter"></i> Twitter</a></li>
                    <li><a href="#" target="_blank"><i class="fab fa-instagram"></i> Instagram</a></li>
                    <li><a href="#" target="_blank"><i class="fab fa-linkedin"></i> LinkedIn</a></li>
                </ul>
            </div>
            <!-- İletişim Bilgileri -->
            <div class="col-md-4 footer-section">
                <h4>İletişim Bilgileri</h4>
                <address class="footer-contact">
                    <strong>Adres:</strong> Mustafa Kemal Mahallesi 694/23 Sokak Buca/İzmir<br>
                    <strong>Email:</strong> keremozkann2004@hotmail.com<br>
                    <strong>Telefon:</strong> +90 507 425 59 54
                </address>
            </div>
        </div>
    </div>
</footer>

    <script src="https://code.jquery.com/jquery-3.6.4.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.6.2/js/bootstrap.min.js"></script>
    
</body>
</html>

btkakademidjangoatolye2024/restoran/templates/restoran/detail.html
{% extends 'restoran/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img height ="300px"src="{{ item.item_image }}" class="card" />

        </div>    

        <div class="col-md-6">
            <h1>{{object.item_name }}</h1>
            <h2>{{object.item_description}}</h2>
            <h3>{{object.item_price}}₺</h3>
            {% if user.is_authenticated %}
            <a class= 'btn-danger' href="{% url 'restoran:delete_item' item.id %}">Sil</a>
            {% endif %}
        </div>    
    </div>   

</div>    


{% endblock %}

btkakademidjangoatolye2024/restoran/templates/restoran/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.6.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <title>Your Website</title>
    
    

</head>
<body>

    <!-- Content -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <!-- Hızlı Linkler -->
                <div class="col-md-4 footer-section">
                    <h4>Hızlı Linkler</h4>
                    <ul class="list-unstyled footer-links">
                        <li><a href="#">Anasayfa</a></li>
                        <li><a href="#">Hakkımızda</a></li>
                        <li><a href="#">Hizmetler</a></li>
                        <li><a href="#">İletişim</a></li>
                    </ul>
                </div>
                <!-- Sosyal Medya -->
                <div class="col-md-4 footer-section">
                    <h4>Sosyal Medya</h4>
                    <ul class="list-unstyled footer-social">
                        <li><a href="#" target="_blank"><i class="fab fa-facebook"></i> Facebook</a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-twitter"></i> Twitter</a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-instagram"></i> Instagram</a></li>
                        <li><a href="#" target="_blank"><i class="fab fa-linkedin"></i> LinkedIn</a></li>
                    </ul>
                </div>
                <!-- İletişim Bilgileri -->
                <div class="col-md-4 footer-section">
                    <h4>İletişim Bilgileri</h4>
                    <address class="footer-contact">
                        <strong>Adres:</strong> Mustafa Kemal Mahallesi 694/23 Sokak Buca/İzmir<br>
                        <strong>Email:</strong> keremozkann2004@hotmail.com<br>
                        <strong>Telefon:</strong> +90 507 425 59 54
                    </address>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.4.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.6.2/js/bootstrap.min.js"></script> 
    
</body>
</html>

btkakademidjangoatolye2024/restoran/templates/restoran/index.html
{% extends 'restoran/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sedat Kerem ÖZKAN</title>
   
</head>
<body>

    {% block body %}
    {% for item in item_list %}   
        <div class='row'>
          <div class="col-md-3 offset-md-2">
            <img class="card" height="150px" src="{{ item.item_image }}"/>
         
          </div> 
          <div class="col-md-4">
            <h3>{{ item.item_name }}</h3>
            <h5>{{ item.item_description }}</h5>
            <h6>{{ item.item_price }}₺</h6>
            <h6>{{ item.user_name }}</h6>
          </div> 
          <div class="col-md-2">
               <a href ="{% url 'restoran:detail' item.id %}" class="btn btn-success">Detaylar</a>          
          </div> 
         
         </div>           
    {% endfor %}
    
    {% endblock %}
   
   
   
   
   
   





    <ul>
      <li>
      <a href=""> {{ item.id }} -- {{ item.item_name}}</a>
      </li>
   </ul>   

        
</body>
</html>


    {% comment %} /restoran/{{ item.id }} HARDCODE URL BAKIM GÜÇLÜĞÜ VE ESNEKLİK EKSİKLİĞİNDEN DOLAYI SİLİNDİ :/ {% endcomment %}
    
    

    

btkakademidjangoatolye2024/restoran/templates/restoran/item-delete.html
{% extends 'restoran/base.html' %}

{% block body %}

{% if user.is_authenticated %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-danger">
                   <div class="card-title">
                      Bu ürünü silmek istediğinize emin misiniz? 
                   </div>
                </div>  
                <div class="card-body">
                    <form method='POST'>
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn-danger" type="submit">Ürünü Sil..</button>
                    </form>    
                </div>    
            </div>    
        </div>
    </div>
</div> 
{% else %}
<h1>SİLME İŞLEMİ İÇİN KULLANICI GİRİŞİ YAPINIZ.</h1>
{% endif %}       
{% endblock %}

btkakademidjangoatolye2024/restoran/templates/restoran/item-form.html
{% extends 'restoran/base.html' %}

{% block body %}



<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                   <div class="card-title">
                      Ürün Ekle 
                   </div>
                </div>  
                <div class="card-body">
                    <form method='POST'>
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn-info" type="submit">Ekle</button>
                    </form>    
                </div>    
            </div>    
        </div>
    </div>
</div>        
{% endblock %}

btkakademidjangoatolye2024/restoran/templates/restoran/item_detail.html
<!-- restoran/templates/restoran/item_detail.html -->
{% extends 'restoran/base.html' %}

{% block body %}
  <div class="container">
    <h1>{{ item.item_name }}</h1>
    <p>{{ item.item_description }}</p>
    <p>Price: {{ item.item_price }}₺</p>

    {% if user.is_authenticated %}
      <a href="{% url 'restoran:add_comment' item_id=item.id %}">Yorum Yap</a>
    {% else %}
      <p>Giriş yapmadınız. Yorum yapabilmek için <a href="{% url 'login' %}">giriş yapın</a>.</p>
    {% endif %}

    <h2>Yorumlar</h2>
    {% for comment in comments %}
      <p>{{ comment.text }} - {{ comment.user.username }} ({{ comment.created_at }})</p>
    {% endfor %}

    {% if comments %}
      <p>Toplam {{ comments.count }} yorum bulunmaktadır.</p>
    {% else %}
      <p>Henüz yorum yapılmamış.</p>
    {% endif %}
  </div>
{% endblock %}